### PR TITLE
Use :coffee as filter name for RubyMine and HAML4+ compatibility

### PR DESCRIPTION
**Pull request by bbuchalter**

### CODE REVIEW

**Comment by paulnicholson** [comment]
I don't think there is any reason to use this gem with haml 4+

**Comment by paulnicholson** [comment]
@bbuchalter Can you explain your use case and why the built-in coffee script filter that shipped with haml 4+ is not working for you or were you unaware that they built it in?

**Comment by bbuchalter** [comment]
But if using this gem and then upgrading to haml4, code changes would be required. Using the haml4 convention makes upgrade as simple as removing the gem.

**Comment by paulnicholson** [comment]
@bbuchalter The [haml docs](http://haml.info/docs/yardoc/file.REFERENCE.html#coffee-filter) state that you can use :coffeescript as well. Does that not work any more? (I have not used haml in a while)

**Comment by bbuchalter** [comment]
You are correct. This PR is unnecessary. The [real issue](http://youtrack.jetbrains.com/issue/RUBY-15520) seems to be with Rubymine not supporting the `:coffeescript` filter. Thanks for the quick response and your contribution to OSS.

**Comment by paulnicholson** [comment]
cool! Thanks for taking the time to contribute as well!

**Pull request closed without merging**
